### ISSUE TITLE
Not working according to README instructions

### ISSUE THREAD

**Issue by edsadr** [fmizzell/systemizer#1]
After generate the code, it requires a new composer update as at the /app directory a new dependency is created, this should be at the README for sure

**Comment by edsadr** [comment]
nevermind ... used composer install instead of update

**Comment by fmizzell** [comment]
That instruction is in the read me, but any suggestion to make it more clear is appreciated

**Comment by edsadr** [comment]
it was not too clear for me, but you are right the instruction is there
